name: release

on:
  push:
    tags:
      - 'v*'   # or '*' if you don't want the v prefix

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Build amd64
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 \
            go build -trimpath -ldflags "-s -w" -o dist/cloudflare-dns-failover_linux_amd64 .

      - name: Build arm64
        run: |
          GOOS=linux GOARCH=arm64 CGO_ENABLED=0 \
            go build -trimpath -ldflags "-s -w" -o dist/cloudflare-dns-failover_linux_arm64 .

      - name: Package
        run: |
          cd dist
          tar -czf cloudflare-dns-failover_${GITHUB_REF_NAME}_linux_amd64.tar.gz cloudflare-dns-failover_linux_amd64
          tar -czf cloudflare-dns-failover_${GITHUB_REF_NAME}_linux_arm64.tar.gz cloudflare-dns-failover_linux_arm64
          sha256sum *.tar.gz > sha256sums.txt

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
